### ISSUE TITLE
改修タスク一覧

### ISSUE THREAD

**Issue by xketanaka** [NaCl-Ltd/intern-2023-A#1]
#### 超かんたん

- [x]  テキストを変える #2

- [x] テキストを変える（設定ファイルに記載された文を表示する） #3
- [x] 色を変える #4
- [x] アイコンを変える #5
- [x] アプリの日本語化（ベタ抱き） #6
- [x] ポストされた画像を表示するときの最大幅を変更 #8

#### やさしめ

- [x] アプリの多言語化（i18n化） #7
- [x] プロフィールに自己紹介文を追加、ユーザ一覧／詳細画面にプロフィールを表示する #9
- [x] 指定したマイクロポストをユーザのフィード画面の一番上に常に表示させる機能 #10
- [x] ~~最新の10件だけ表示する、もっと見るリンクで11件目以降が表示される #11~~
- [x] 最近投稿されたマイクロポスト10件を表示（NEWメニュー）  #12
- [x] ユーザ一覧に検索機能を追加（ユーザ名またはメールアドレスの部分一致） #13

#### 中くらい

- [x] 画像を複数アップロード可能にする #14
- [x] マイクロポストの削除後に復活できるようにする #15
- [x] URLをポストしたらリンクになるように #16
- [ ] プロフィールにニックネームを追加。またニックネームがポストされたらその人へのリンクとする #17
- [ ] プロフィールに出身地を追加。ユーザ一覧で出身地に絞り込む機能を追加 #18
- [x] フォロワーのフォロー数・されてる数を表示する #19
- [ ] 管理者機能：他人のマイクロポストを削除できる #20

#### むずかしい

- [x] Like機能の追加 #21
    - [x] 自分がLikeしたマイクロポストを一覧表示する機能
    - [x] あるマイクロポストをLikeしたユーザを一覧表示する機能
    - [x] マイクロポストにLike数を表示する機能
- [ ] Share機能の追加 (TwitterにおけるRT的なもの)
    - [ ] フォローしているユーザがShareしたマイクロポストをフィードに表示する機能
    - [ ] マイクロポストにShare数を表示する機能
- [ ] 通知機能
    - [ ] 通知機能の実装
        - [ ] メール通知とかでなくていい
        - [ ] 手段は問わない
            - [ ] flashメッセージで「通知がN件あります」とかが簡単かな
            - [ ] 通知バッジ的なものをしてもいいけど難しいと思う
    - [ ] 通知一覧画面の実装
        - [ ] 一度表示した通知はもう通知欄に表示しないようにする
    - [ ] マイクロポストがLikeされたときに通知を追加する機能
    - [ ] マイクロポストがShareされたときに通知を追加する機能
    - [ ] フォローされたときに通知を追加する機能
- [x] ユーザ検索機能
    - [x] アカウント名に指定した文字列を含むユーザのみの一覧を表示する機能
- [ ] ダイレクトメッセージ機能
